packages:
  - packages/*
  - apps/*

catalog:
  '@biomejs/biome': 2.3.8
  '@effect-atom/atom-react': ^0.4.4
  '@effect/language-service': ^0.62.0
  '@effect/opentelemetry': ^0.59.3
  '@effect/platform': ^0.93.6
  '@effect/platform-browser': ^0.73.0
  '@effect/platform-node': ^0.103.0
  '@effect/rpc': ^0.72.2
  '@effect/sql': ^0.48.6
  '@effect/sql-drizzle': ^0.47.0
  '@effect/sql-pg': ^0.49.7
  '@effect/vitest': ^0.27.0
  '@radix-effects/gateway': ^0.5.0
  '@radix-effects/shared': ^0.0.1
  '@radixdlt/babylon-gateway-api-sdk': ^1.10.1
  '@types/node': ^25.0.0
  bignumber.js: ^9.3.1
  drizzle-orm: 0.45.1
  effect: 3.19.11
  sbor-ez-mode: ^0.2.0
  tsdown: ^0.17.2
  tsx: ^4.21.0
  typescript: ^5.7.2
  vite: ^7.1.7
  vitest: 3.2.4
