/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TcIndexRouteImport } from './routes/tc/index'
import { Route as TcNewIndexRouteImport } from './routes/tc/new/index'
import { Route as TcIdIndexRouteImport } from './routes/tc/$id/index'
import { Route as ProposalIdIndexRouteImport } from './routes/proposal/$id/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TcIndexRoute = TcIndexRouteImport.update({
  id: '/tc/',
  path: '/tc/',
  getParentRoute: () => rootRouteImport,
} as any)
const TcNewIndexRoute = TcNewIndexRouteImport.update({
  id: '/tc/new/',
  path: '/tc/new/',
  getParentRoute: () => rootRouteImport,
} as any)
const TcIdIndexRoute = TcIdIndexRouteImport.update({
  id: '/tc/$id/',
  path: '/tc/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProposalIdIndexRoute = ProposalIdIndexRouteImport.update({
  id: '/proposal/$id/',
  path: '/proposal/$id/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tc': typeof TcIndexRoute
  '/proposal/$id': typeof ProposalIdIndexRoute
  '/tc/$id': typeof TcIdIndexRoute
  '/tc/new': typeof TcNewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tc': typeof TcIndexRoute
  '/proposal/$id': typeof ProposalIdIndexRoute
  '/tc/$id': typeof TcIdIndexRoute
  '/tc/new': typeof TcNewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/tc/': typeof TcIndexRoute
  '/proposal/$id/': typeof ProposalIdIndexRoute
  '/tc/$id/': typeof TcIdIndexRoute
  '/tc/new/': typeof TcNewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/tc' | '/proposal/$id' | '/tc/$id' | '/tc/new'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/tc' | '/proposal/$id' | '/tc/$id' | '/tc/new'
  id: '__root__' | '/' | '/tc/' | '/proposal/$id/' | '/tc/$id/' | '/tc/new/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TcIndexRoute: typeof TcIndexRoute
  ProposalIdIndexRoute: typeof ProposalIdIndexRoute
  TcIdIndexRoute: typeof TcIdIndexRoute
  TcNewIndexRoute: typeof TcNewIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tc/': {
      id: '/tc/'
      path: '/tc'
      fullPath: '/tc'
      preLoaderRoute: typeof TcIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tc/new/': {
      id: '/tc/new/'
      path: '/tc/new'
      fullPath: '/tc/new'
      preLoaderRoute: typeof TcNewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tc/$id/': {
      id: '/tc/$id/'
      path: '/tc/$id'
      fullPath: '/tc/$id'
      preLoaderRoute: typeof TcIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proposal/$id/': {
      id: '/proposal/$id/'
      path: '/proposal/$id'
      fullPath: '/proposal/$id'
      preLoaderRoute: typeof ProposalIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TcIndexRoute: TcIndexRoute,
  ProposalIdIndexRoute: ProposalIdIndexRoute,
  TcIdIndexRoute: TcIdIndexRoute,
  TcNewIndexRoute: TcNewIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
