import { Schema } from 'effect'
import s from 'sbor-ez-mode'

// Generated TypeScript schema for Scrypto SBOR types of package address: package_rdx1phf3dup836zgc05p248j24m879dg09ktld6nlej23wdrru7ksrkxlg
// Generated by: https://www.8arms1goal.com/sbor-ez-mode-ez-mode

export const VoteDelegation = s.struct({
  delegatees: s.internalAddress(),
  delegators: s.internalAddress()
})

export const GovernanceParameters = s.struct({
  temperature_check_days: s.number(),
  temperature_check_quorum: s.decimal(),
  temperature_check_approval_threshold: s.decimal(),
  proposal_length_days: s.number(),
  proposal_quorum: s.decimal(),
  proposal_approval_threshold: s.decimal()
})

export const Governance = s.struct({
  governance_parameters: GovernanceParameters,
  temperature_checks: s.internalAddress(),
  temperature_check_count: s.number(),
  proposals: s.internalAddress(),
  proposal_count: s.number()
})

export const TemperatureCheckKeyValueStoreKey = s.number()

export const TemperatureCheckKeyValueStoreValue = s.struct({
  title: s.string(),
  short_description: s.string(),
  description: s.string(),
  vote_options: s.array(
    s.struct({
      id: s.tuple([s.number()]),
      label: s.string()
    })
  ),
  links: s.array(s.string()),
  quorum: s.decimal(),
  max_selections: s.enum([
    {
      variant: 'None',
      schema: s.structNullable({})
    }
  ]),
  voters: s.internalAddress(),
  votes: s.internalAddress(),
  vote_count: s.number(),
  approval_threshold: s.decimal(),
  start: s.number(),
  deadline: s.number(),
  elevated_proposal_id: s.enum([
    {
      variant: 'None',
      schema: s.structNullable({})
    }
  ]),
  author: s.address()
})

export const KeyValueStoreAddress = Schema.String.pipe(
  Schema.brand('KeyValueStoreAddress')
)

export type KeyValueStoreAddress = typeof KeyValueStoreAddress.Type

export const TemperatureCheckVoteKeyValueStoreKey = s.number()

export const TemperatureCheckVote = s.enum([
  { variant: 'For', schema: s.tuple([]) },
  { variant: 'Against', schema: s.tuple([]) },
  { variant: 'Abstain', schema: s.tuple([]) }
])

export const TemperatureCheckVoteKeyValueStoreValue = s.struct({
  voter: s.address(),
  vote: TemperatureCheckVote
})

export const TemperatureCheckVotersKeyValueStoreKey = s.address()

export const TemperatureCheckVotersKeyValueStoreValue = s.number()

export const ProposalVoteOptionId = s.tuple([s.number()])

export const TemperatureCheckVotedEvent = s.struct({
  temperature_check_id: s.number(),
  vote_id: s.number(),
  account: s.address(),
  vote: TemperatureCheckVote
})

export const ProposalCreatedEvent = s.struct({
  proposal_id: s.number(),
  temperature_check_id: s.number(),
  title: s.string(),
  start: s.instant(),
  deadline: s.instant()
})

export const ProposalVotedEvent = s.struct({
  proposal_id: s.number(),
  vote_id: s.number(),
  account: s.address(),
  options: s.array(ProposalVoteOptionId)
})

export const TemperatureCheckCreatedEvent = s.struct({
  temperature_check_id: s.number(),
  title: s.string(),
  start: s.instant(),
  deadline: s.instant()
})
