import { Schema } from 'effect'
import s from 'sbor-ez-mode'
// Generated TypeScript schema for Scrypto SBOR types of package address: package_rdx1phf3dup836zgc05p248j24m879dg09ktld6nlej23wdrru7ksrkxlg
// Generated by: https://www.8arms1goal.com/sbor-ez-mode-ez-mode

export const VoteDelegation = s.struct({
  delegatees: s.internalAddress(),
  delegators: s.internalAddress()
})

export const GovernanceParameters = s.struct({
  temperature_check_days: s.number(),
  temperature_check_quorum: s.decimal(),
  temperature_check_approval_threshold: s.decimal(),
  proposal_length_days: s.number(),
  proposal_quorum: s.decimal(),
  proposal_approval_threshold: s.decimal()
})

export const Governance = s.struct({
  governance_parameters: GovernanceParameters,
  temperature_checks: s.internalAddress(),
  temperature_check_count: s.number(),
  proposals: s.internalAddress(),
  proposal_count: s.number()
})

export const TemperatureCheckKeyValueStoreKey = s.number()

export const TemperatureCheckKeyValueStoreValue = s.struct({
  title: s.string(),
  description: s.string(),
  vote_options: s.array(
    s.struct({
      id: s.tuple([s.number()]),
      label: s.string()
    })
  ),
  attachments: s.array(
    s.struct({
      kvs_address: s.string(),
      component_address: s.address(),
      file_hash: s.string()
    })
  ),
  rfc_url: s.string(),
  quorum: s.decimal(),
  max_selections: s.enum([
    {
      variant: 'None',
      schema: s.structNullable({})
    }
  ]),
  votes: s.internalAddress(),
  approval_threshold: s.decimal(),
  start: s.number(),
  deadline: s.number(),
  elevated_proposal_id: s.enum([
    {
      variant: 'None',
      schema: s.structNullable({})
    }
  ])
})

export const KeyValueStoreAddress = Schema.String.pipe(
  Schema.brand('KeyValueStoreAddress')
)

export type KeyValueStoreAddress = typeof KeyValueStoreAddress.Type

export const TemperatureCheckVoteKeyValueStoreKey = s.address()

export const TemperatureCheckVoteKeyValueStoreValue = s.enum([
  {
    variant: 'For',
    schema: s.structNullable({})
  },
  {
    variant: 'Against',
    schema: s.structNullable({})
  }
])
